### ISSUE TITLE
Programs stucked with "submitting 5 warmup jobs" printed.

### ISSUE THREAD

**Issue by LaceFern** [p4lang/p4app-switchML#11]
Hello. I ran allreduce_benchmark on two servers and found that both programs stucked with "submitting 5 warmup jobs" printed on the console. I had checked that in the switchml.cfgs on both servers, the num_workers was 2, and the rank was 0 for one while 1 for the other. What should I do next to debug it? Thanks in advance for any help!

**Comment by OasisArtisan** [comment]
Thank you for getting in touch.
The reason why it took us so long to respond is because you did not include enough information for us to be able to help you.

If you are still having this problem please reopen it and send us the configuration file that you are using, what type of backend you want to test with, and what steps did you take to compile and setup the SwitchML components.
