### ISSUE TITLE
Question about folded_pipe.

### ISSUE THREAD

**Issue by Catchher** [p4lang/p4app-switchML#19]
Hi, I notice that the current project only supports folded_pipe1 and folded_pipe 4. Can I modify the code to support **folded_pipe 2**？

**Comment by AmedeoSapio** [comment]
Hi, 
yes, the current code supports one pass through Tofino to process 64 elements per packet (256B), and 4 passes to process 256 elements (1KB). This means either using 1 pipe or 4 pipes. It is surely possible to add support for 512B packets using 2 pipes. This can be supported by both the DPDK and RDMA backends, since ibverbs have a 512B MTU option (see [here](https://github.com/linux-rdma/rdma-core/blob/e97b3986c0fb28eb8a2275befeb808f46e98da19/libibverbs/verbs.h#L364-L370)).

The main changes that are needed are in the next_step_selector entries to make the packet go through the right sequence of ports

https://github.com/p4lang/p4app-switchML/blob/b5c74a04fa66faa82acab154a4e21c8f76d913f2/dev_root/controller/next_step_selector.py#L85-L86

and the client library to make it work with 512B/128 elements per packet. Some parts of the code is already there, see the DPDK backend:

https://github.com/p4lang/p4app-switchML/blob/b5c74a04fa66faa82acab154a4e21c8f76d913f2/dev_root/client_lib/src/backends/dpdk/dpdk_worker_thread_utils.inc#L113-L122

and the P4 program:
https://github.com/p4lang/p4app-switchML/blob/b5c74a04fa66faa82acab154a4e21c8f76d913f2/dev_root/p4/types.p4#L128-L133

but we haven't tested it, and probably there are other things to change, like in the RDMA backend where we don't consider it an option: 
https://github.com/p4lang/p4app-switchML/blob/b5c74a04fa66faa82acab154a4e21c8f76d913f2/dev_root/client_lib/src/backends/rdma/rdma_connection.cc#L65

Are you considering adding this feature?

**Comment by Catchher** [comment]
Yes, But it seems not easy for me. I modified the code in next_step_selector.py, and I guess i make a mistake, because I don't know what's the correct steps to realize folded pipe2 and as the controler shows, switch only recieve packets, doesn't send.
```
port = {4: 196, 5: 192, 6: 64, 7: 68}

        # yapf: disable
        entries = [
            # packet_size | worker_id | packet_type | first_last_flag | bitmap_result | priority | action | port |
            ( PacketSize.MTU_128, None,                None,       None, None, 0, 'drop', None),
            ( PacketSize.MTU_256, None, PacketType.CONSUME0,  Flag.LAST, None, 1, 'recirculate_for_HARVEST7', port[7]),
            ( PacketSize.MTU_256, None, PacketType.CONSUME0,       None,    0, 2, 'finish_consume', None),
            ( PacketSize.MTU_256, None, PacketType.CONSUME0, Flag.FIRST, None, 3, 'recirculate_for_HARVEST7', port[7]),
            ( PacketSize.MTU_256, None, PacketType.CONSUME0,       None, None, 4, 'drop', None),
            ( PacketSize.MTU_1024, None,                None,       None, None, 5, 'drop', None)]

        if self.folded_pipe:
            ## 1024B packets
            entries.extend([
                ## Pipe 0, packet not seen before -> pipe 1 (load balance on worker id)
                (PacketSize.MTU_512,    i, PacketType.CONSUME0,       None,    0, 6, 'recirculate_for_CONSUME1', (1 << 7) + i * 4)
                for i in range(16)])
            entries.extend([
                ## Pipe 0, retransmitted packet to a full slot -> pipe 1
                ## Run through the same path as novel packets (do not skip to harvest) to ensure ordering
                (PacketSize.MTU_512,    i, PacketType.CONSUME0, Flag.FIRST, None, 7, 'recirculate_for_CONSUME1', (1 << 7) + i * 4)
                for i in range(16)])
            entries.extend([
                ## Drop other CONSUME0 packets
                (PacketSize.MTU_512, None, PacketType.CONSUME0,       None, None, 8, 'drop', None),
                (PacketSize.MTU_512, None, PacketType.CONSUME1,  Flag.LAST, None, 9, 'recirculate_for_HARVEST1', port[4]),
                (PacketSize.MTU_512, None, PacketType.CONSUME1,       None,    0, 10, 'finish_consume', None),
                (PacketSize.MTU_512, None, PacketType.CONSUME1,  Flag.FIRST, None, 11, 'recirculate_for_HARVEST1', port[4]),
                (PacketSize.MTU_512, None, PacketType.CONSUME1,       None, None, 12, 'drop', None),
                (PacketSize.MTU_512, None, PacketType.HARVEST1,       None, None, 14, 'recirculate_for_HARVEST2', port[5]),
                (PacketSize.MTU_512, None, PacketType.HARVEST2,       None, None, 15, 'recirculate_for_HARVEST3', port[6]),
                (PacketSize.MTU_512, None, PacketType.HARVEST3,       None, None, 16, 'recirculate_for_HARVEST7', port[7])])

```

**Comment by Catchher** [comment]
But I'll go ahead and implement it, any suggestion would be helpful. THANKS.

**Comment by Catchher** [comment]
@AmedeoSapio Hi,
I modified the relevant code according to your suggestions, and then successfully ran the test program, and the data verification of the test program passed. 2 folding is **6%** faster than 1 folding. Can this show that my 2-fold pipeline has been successfully implemented?
Finally, can I implement 4-fold pipes on a 2-pipe switch? I tried to modify the relevant ports, but the result observed on the switch side is that the packets only pass through the ports of consulme0 and consulme1, and the ports from consulm1 to consulme2 are not available, no matter what port value I set.
Following is the code I modified and the original code respectively.
```
    action recirculate_for_CONSUME2_same_port_next_pipe(PortId_t recirc_port) {
        recirculate_for_consume(packet_type_t.CONSUME2, recirc_port);
    }

    action recirculate_for_CONSUME3_same_port_next_pipe(PortId_t recirc_port) {
        recirculate_for_consume(packet_type_t.CONSUME3, recirc_port);
    }
```
Moreover. I will choose a recirculated port to replace `2w2 ++ ig_intr_md.ingress_port[6:0]` or `2w3 ++ ig_intr_md.ingress_port[6:0]`.
```
    action recirculate_for_CONSUME2_same_port_next_pipe() {
        recirculate_for_consume(packet_type_t.CONSUME2, 2w2 ++ ig_intr_md.ingress_port[6:0]);
    }

    action recirculate_for_CONSUME3_same_port_next_pipe() {
        recirculate_for_consume(packet_type_t.CONSUME3, 2w3 ++ ig_intr_md.ingress_port[6:0]);
    }
```

**Comment by Catchher** [comment]
I have implemented 2-folded pipeline successfully. Thanks. @AmedeoSapio
