### ISSUE TITLE
Unable to run multiple SwitchML instances on same machine   

### ISSUE THREAD

**Issue by kfertakis** [p4lang/p4app-switchML#28]
Hi,

I'm trying to utilize both of my MLX5 NIC's ports for an experiment and I'm having trouble running the `allreduce_benchmark` when two instances are executed on the same machine. I have programmatically set the configuration for each instance by overloading the client library constructor to accept a configuration file path. I'm thus explicitly telling one instance to use `mlx5_0` and the other `mlx5_1`. However, the execution seems to hang after `Submitting 5 warmup jobs.`, so jobs never finish. Is there perhaps a specific reason why two instances of SwitchML jobs cannot start on the same machine? Is somehow the client lib a singleton and cannot support multiple SwitchML jobs on different NIC ports? 

Thanks

**Comment by lq470379** [comment]
Did you manage to get this work? I ran to the same problem :/

**Comment by kfertakis** [comment]
No, I gave up on this endeavor, unfortunately. I think there was a more fundamental issue with the local IP routing tables of the host as it was discarding packets received on one interface sent from the other, presumably as it thought it could contact them locally. Maybe network namespaces could help in making this work. I would be interested to know if you make it happen @lq470379 .

**Comment by AmedeoSapio** [comment]
I never tried this myself, so I would be interested in knowing what the problem is. 
Is there any relevant information in the log? We use glog, so you can use the `GLOG_v=2 GLOG_logtostderr=1` environment variables to see the logs, and you will see more info when compiling with the DEBUG flag.

This issue also depends on what backend you are using. For DPDK there are some flags (like `--file-prefix`) that you can use to run multiple processes. See [here](https://doc.dpdk.org/guides/prog_guide/multi_proc_support.html) for more details. You can use the `extra_eal_options` parameter in the config file to pass these DPDK flags. 

For RDMA, it can be that is happening what @kfertakis said. The RDMA packets never really go outside the server, because they use an internal loopback. Using different network namespaces should solve this problem. 
Another problem with the RDMA backend is that we allocate the memory at a fixed address (`1L << 44`) in the hugepages space, so different processes may end up working on the same memory. This can be solved changing this address, to have different addresses for the 2 processes or, even better, making it a configuration parameter. 

https://github.com/p4lang/p4app-switchML/blob/b5c74a04fa66faa82acab154a4e21c8f76d913f2/dev_root/client_lib/src/backends/rdma/rdma_connection.cc#L79-L80
