### ISSUE TITLE
Using multiple pipes on the same job

### ISSUE THREAD

**Issue by kfertakis** [p4lang/p4app-switchML#34]
Hi,

This issue is related to #33. I am using a BF2556-1T switch with two pipes on the Tofino chip and I'm trying to use its QSFP front panel ports which are unfortunately split between pipe 1 and pipe 3 of the switch. Since I'm not using the folded pipe option, I've changed the parser logic in order to not reserve pipes 1-3 for recirculation as follows:

```
    state parse_port_metadata {
        // parse port metadata
        ig_md.port_metadata = port_metadata_unpack<port_metadata_t>(pkt);

        transition select(ig_intr_md.ingress_port) {
            64: parse_recirculate; // pipe 0 CPU Eth port
            68: parse_recirculate; // pipe 0 recirc port
            320: parse_ethernet;   // pipe 2 CPU PCIe port
            // 0x080 &&& 0x180: parse_recirculate; // all pipe 1 ports
            // 0x100 &&& 0x180: parse_recirculate; // all pipe 2 ports
            // 0x180 &&& 0x180: parse_recirculate; // all pipe 3 ports
            default:  parse_ethernet;
        }
    }
```

However, when I execute a job including workers on different pipes, the execution hangs with packets arriving in the switch but no packet is being sent back to the workers as can be seen in the following:

![image](https://user-images.githubusercontent.com/22995161/203784541-2dd066bb-88e2-4c14-ac36-435867ec3e4b.png)

and this is what the bitmap looks like (it seems to be stuck in these values under repeated queries to it):

<img width="616" alt="image" src="https://user-images.githubusercontent.com/22995161/203786140-51b08f9b-f1af-4487-bc3d-7b65e3fa2af4.png">

Is concurrent execution on both pipes feasible? If so, what modifications are required? Is perhaps the fact that registers(for CONSUME and HARVEST) are pipe local somehow related to this? Thank you.

**Comment by AmedeoSapio** [comment]
Hi,
yes, it is not possible to support workers connected to different pipes participating in the same job.
The current code uses both a bitmap and a counter to mark workers' contributions. 
The bitmap is used to set a bit every time a new packet from a worker is received, in order to identify retransmissions. 
A separate counter is used to count how many workers sent their contribution, to find out when all workers have sent their data. 
Both the bitmap and the counter are implemented using registers, which in Tofino 1 are pipe-local. 
In you case, the counter is incremented in different pipes, so the switch never sees a value equal to N (= number of workers), so it never sends data back to the workers.

**Comment by kfertakis** [comment]
I see, this makes a lot of sense. Thank you for the explanation.
