### ISSUE TITLE
About GDR support

### ISSUE THREAD

**Issue by VoidStardust** [p4lang/p4app-switchML#39]
Hello,
I noticed that you have removed the options related to GDR in the most recent commit b5c74a0. May I ask if you have abandoned support for GDR?
I believe GDR is crucial for GPU training. Without specific optimizations, the copy overhead from device to host can severely impact the performance of AllReduce between multiple machines. So I really hope to see GDR being supported by SwitchML.

**Comment by OasisArtisan** [comment]
Hey apologies for the late reply,

If memory serves me right, the reliance on the CPU only exists in the "prepostprocessor". If you implement one that does SwitchML quantization directly on GPU memory then modify the integrations with PyTorch or Tensorflow so that they pass you the GPU pointers directly you should be able to make GPU direct work. No other modifications are needed.
