### ISSUE TITLE
How to disable ICRC on RNICs?

### ISSUE THREAD

**Issue by MrGaoxx** [p4lang/p4app-switchML#5]
Hi i am very interested in the RDMA-based implementation.
Could u tell me how to disable ICRC on RNICs (referred in README)?

**Comment by AmedeoSapio** [comment]
Hi, thanks for the interest in this project. 

Unfortunately, the way in which ICRC checking is disabled changes depending on the manufacturer and model of the NIC. 

There is a script [here](https://github.com/p4lang/p4app-switchML/blob/main/dev_root/scripts/disable-icrc.sh) that works to disable ICRC checking on Mellanox Connect-X 5 and 6.

If you have a different NIC, probably the best way to find it out is to contact the manufacturer customer support. If you find out how to do this in a different NIC, we will be very happy if you can share that with us, so that we can add it to the documentation, it might be useful for other people with the same problem.

**Comment by kfertakis** [comment]
Hi,

is there a way to disable ICRC on a Mellanox Connect-X 4 device? Thank you.

**Comment by AmedeoSapio** [comment]
Hi, 
I think there is, but it is done using different registers than the ConnectX-5 and 6. 
The registers are the ones in the `REGS` variable in the provided script. I don't know the exact register numbers for ConnectX 4, the Mellanox/Nvidia's customer support is probably the best source for this.

**Comment by hamedsey** [comment]
Hi,

By any chance, have you been able to disable iCRC validation on ConnectX-6 Dx. The script above didn't work for me.

Thank you, in advance!!

**Comment by toddwilde** [comment]
Hi,

This script was really helpful to us in a custom RoCE development with an FPGA.  I also am having issues with ConnectX-6 not working though.  If there is a ConnectX-6 solution I would be very grateful to get it.   I am trying to find equivalent solution through nVidia, but haven't had any success yet.

Thanks,
Todd

**Comment by AmedeoSapio** [comment]
I have tested the script with a ConnectX-6 VPI (MT28908 Family) and it worked. Maybe the Dx model uses different registers. 
Please let us know in case nvidia provides a solution, so that we can add it to the documentation.

**Comment by maximilianheer** [comment]
Hi! 

I just tried to run this script to disable ICRC on a Mellanox ConnectX-5 Ex (MT28800 Family), but had the issue that the values of the device registers couldn't be changed to 0x0 - the read-out of the values before and after attempting to write are exatly the same. Have you maybe seen something like that before or possibly know a way around this? 

Thanks a lot in advance for your help (and for sharing this script in the first place)!

Best,

Max.

**Comment by amir-raoofy** [comment]
Has anyone succeeded in disabling ICRC validation on ConnectX-6 Dx?
