### ISSUE TITLE
hello_world example not sending any traffic

### ISSUE THREAD

**Issue by kfertakis** [p4lang/p4app-switchML#8]
Hi,

I am trying to benchmark SwitchML and I have managed to compile the P4 program and deploy it on the switch. I am also running the controller on the switch directly and I have connected two different machines on the switch and I'm trying to run the hello_world example. I have modified the `switchml.cfg` file accordingly by setting the backend to `rdma` and the relevant values for the rest (`num_workers=2`). However, when I start the example from the two different machines, they manage to connect with the controller running on the switch but they seem to hang afterwards waiting for the jobs to finish. Specifically, the output of the program is the following:

```
Hello world!. Starting the switchml context
Allocating data
Initializing data
Submiting all reduce jobs
Waiting for all jobs to finish
```

On the controller side, I am able to query with `show_rdma_workers` for which I do get two entries for the workers with the correct worker ids and MACs (the IPs are all 0 but I assume this is because testing over RDMA). However, the counters for received/sent packets are all zero. Furthermore, on the client machines, the TX packets on the corresponding interface do not increase (at least in the short time after the start of execution). This makes me question whether traffic is indeed generated and whether it reaches the switch. Any thoughts perhaps on what could cause this or potential misconfiguration ? Thanks.

Environment:

Tofino Switch: APS Networks BF2556X-1T-A1F
SDE: 9.6.0
Python: 3.8.10
NICs:ConnectX-5 

Thanks

**Comment by AmedeoSapio** [comment]
Hi,
I think this may be due to a misconfiguration. You should use ROCEv2 (`gid_index = 3`) and the IP should not be all zeros, as we get the IP from the GID of the interface and share that with the controller before sending any traffic (we use ROCEv2). This is an example of what you should see in the controller:
```
SwitchML>show_rdma_workers

                                                   Received              Sent
 Worker ID     Worker MAC        Worker IP     Packets  /    Bytes      Packets  /    Bytes
     0      1c:34:da:00:00:00    10.0.0.1         10    /    3380          10    /    3100
     1      1c:34:da:00:00:01    10.0.0.2         10    /    3380          10    /    3100
     2      1c:34:da:00:00:02    10.0.0.3         10    /    3380          10    /    3100
     3      1c:34:da:00:00:03    10.0.0.4         10    /    3380          10    /    3100

```
Maybe there is a problem with the interface configuration. Assuming you want to use port 1 of the interface mlx5_0, you should have this in switchml.cfg:
```
device_name = mlx5_0
device_port_id = 1
gid_index = 3
```
Does the interface mlx5_0 have an IP address? Is the port UP? 
If this does not work, can you share the switchml.cfg file that you are using?

And if you haven't done it already, disable ICRC checking using the provided script (but this has nothing to do with this issue, because ICRC checking does not stop packet transmission).

**Comment by kfertakis** [comment]
Yes, it seems this was indeed a misconfiguration issue. I changed the RDMA mode to RoCEv2 with IP-based GID (`gid_index = 3`) and after setting IP addresses to the mlx5_1 interfaces in both machines, I rerun the program and now the controller is picking up the IP addresses and the packet counters seem to always increase.

However, the program still seems to not finish within a reasonable amount of time. For reference, I'm getting the same output from the hello_world program and this is what I see on the controller:

```
SwitchML>show_rdma_workers

                                                   Received              Sent        
 Worker ID     Worker MAC        Worker IP     Packets  /    Bytes      Packets  /    Bytes    
     0      0c:42:a1:81:1b:8b    10.0.0.1       14908   /  16249720      59632   /  64283296   
     1      0c:42:a1:81:1b:43    10.0.0.3       14908   /  16249720      59248   /  63869344   
```

I have disabled ICRC checking as instructed with the provided scripts. I'm attaching the `switchml.cfg` file of one of the workers for reference. 
[switchml.cfg](https://github.com/p4lang/p4app-switchML/files/8239570/switchml.cfg.txt)

Is there a way of validating whether the aggregation does indeed happen in the switch or checking the job state and why it doesn't finish?

The statistics I'm getting from the controller are the following:

```
SwitchML>show_statistics

             Broadcasted         Recirculated       Retransmitted          Dropped       
  Index    Set 0     Set 1     Set 0     Set 1     Set 0     Set 1     Set 0     Set 1   
    0        1         0         0         0        1169       0         4         0     
    1        1         0         0         0        1169       0         4         0     
    2        1         0         0         0        1169       0         4         0     
    3        1         0         0         0        1169       0         4         0     
    4        1         0         0         0        1169       0         4         0     
    5        1         0         0         0        1169       0         4         0     
    6        1         0         0         0        1169       0         4         0     
    7        1         0         0         0        1169       0         4         0     
```

Thank you,

**Comment by kfertakis** [comment]
It seems I'm experiencing the same issue with the `allreduce` benchmark. The benchmarks starts, submits 5 warmup jobs but stalls afterward. 

The output of the benchmark is:

```
Signal handler thread started. Waiting for any signals. 
Submitting 5 warmup jobs. 
```

It seems, in both cases (`helloworld` and `allreduce` benchmark) I'm stuck at `ctx.WaitForAllJobs();` and the condition variable `all_jobs_finished_event_` is never notified (within a reasonable amount of time). The counters on the controller side seem to be always increasing. Any idea on why this could be happening and the jobs never seem to finish? Thanks.

**Comment by OasisArtisan** [comment]
It seems like you are getting stuck retransmitting packets. Either the packets are not being sent to the switch properly or not being transmitted back properly.

**Things to double check quickly**

- Are you setting rank correctly in the configuration? Each node has its own config with its own rank from 0 to 1?
- Are you compiling with retransmissions ? That is you did not compile with the TIMEOUTS=0 flag?.
- Sometimes restarting the p4 program on the switch can help.

**Things to do to gather more information:**

- You should monitor the switch's counters to see if packets are indeed being received and sent back from the switch's side.
- You can pass GLOG_logtostderr=1 GLOG_v=2 as environment variables when running hello_world or allreduce to see more information being logged. When you get stuck exit using ctrl+c and you should see statistics being printed from the client side on how many packets have been sent/retransmitted. 
- You can also compile switchml with DEBUG=1 VCL=0 to enable debugging messages with verbosity of up to 4 and set GLOG_v=4 but let us leave that for a later stage.

**Comment by kfertakis** [comment]
Yeap, it seems I keep retransmitting packets. 

Switching to a more verbose output as suggested, found these logs being constantly generated:

```
I0315 01:28:44.079278 2226023 rdma_worker_thread.cc:365] Worker thread '3' QP 6:0xefd reposting write from 0x100000186000 length 4096 rkey/slot 1b0
I0315 01:28:44.719130 2226021 rdma_worker_thread.cc:365] Worker thread '2' QP 7:0xeee reposting write from 0x100000107000 length 4096 rkey/slot 138
I0315 01:28:44.719215 2226020 rdma_worker_thread.cc:365] Worker thread '1' QP 7:0xede reposting write from 0x100000087000 length 4096 rkey/slot b8
I0315 01:28:44.719249 2226019 rdma_worker_thread.cc:365] Worker thread '0' QP 7:0xece reposting write from 0x100000007000 length 4096 rkey/slot 38
I0315 01:28:44.719317 2226023 rdma_worker_thread.cc:365] Worker thread '3' QP 7:0xefe reposting write from 0x100000187000 length 4096 rkey/slot 1b8
```

Regarding your points:

- Ranks are set correctly as documented.
- I am not compiling with TIMEOUTS=0 flag.
- From the switch's counters, I can see that packets are indeed received and sent back.

The only thing I didn't get it work is the printing of statistics from the client side in terms of packets sent/retransmitted after ending the example program with ctrl+c. They aren't printed in the glog file either. 

Is there a way of finding if the packets make it back to the example program maybe?

**Comment by AmedeoSapio** [comment]
One problem with your cfg file is `packet_numel = 256`, which means 256 of 32 bits elements per packet = 1KB. This is only supported with the 4 pipes folded pipeline. With a single pipeline the only valid value is `packet_numel = 64`, which is 256B per packet that can be processed in a single pass through Tofino.
Anyway, this is not the cause of your issue, as in this case Tofino will only process the first 256B of a packet and ignore the rest (while giving a warning in the controller log), so the hello world and benchmark will still complete the execution.

I suggest to use a simpler configuration, with a very long timeout, so that we don't have retransmissions polluting the packet counters. See this file as an example (this will have poor performance, but at least should complete the execution): 
[switchml.cfg.txt](https://github.com/p4lang/p4app-switchML/files/8249657/switchml.cfg.txt)

Check also the packet counters in your NIC. The following script will dump all the counters with name and value.
You can run this script before and after the experiment and diff the 2 outputs to check which counters have changed. 

```bash
for f in /sys/class/infiniband/mlx5_1/ports/1/hw_counters/*; do
  echo $f `cat $f`
done
for f in /sys/class/infiniband/mlx5_1/ports/1/counters/*; do
  echo $f `cat $f`
done

ethtool -S <YOUR ETH INTERFACE NAME>
```

**Comment by AmedeoSapio** [comment]
BTW I see that you are using the `mlx5_1` device, so you need to change this line `DEV=mlx5_0` in the `disable-icrc.sh` script to disable "ICRC checking" in the right interface. 
If you have done that already, can you also show the output of `disable-icrc.sh`?

**Comment by AmedeoSapio** [comment]
The fact that the hello world verification fails is expected, because you used `prepostprocessor = bypass`, which means that we disabled the quantization/dequantization, so floats are not converted to a fixed point representation before sending the data to the switch and the aggregation is not done correctly as a result. 

Now that your problem is solved, you can use `prepostprocessor = cpu_exponent_quantizer` to enable quantization and the verification should be successful.

To get to line rate (which is ~75Gbps goodput with packets of this size) with the benchmark, these are the parameters that you need to play with to get better performance. The values are what work in my server, but it depends on the hw, so you may need to adjust them.

```
num_worker_threads = 4
max_outstanding_packets = 256
msg_numel = 1024
```

I found out that if you use `packet_numel = 256` without a folded pipe, automatically falling back to 64 elements per packet doesn't work, because the client isn't aware of that. So I need to either inform the client or just show an error since the configuration is not correct. Thanks for finding this out. 

The received counter always equal to zero is a bug in reading the counters. Thanks for pointing this out, will commit a fix shortly.

**Comment by kfertakis** [comment]
I can confirm that now, after enabling the quantization via the `prepostprocessor` setting and having a `packet_numel=64`, both the `helloworld` example and `allreduce` benchmark execute successfully. Thank you for your help and assistance in this. I hope future adopters can benefit from our discussion as well.
